### ISSUE TITLE
Failed to restore session

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PhotoshopTimeTracker#13]
It happened after a power failure so I believe it was caused by a sudden system shutdown. 
![image](https://user-images.githubusercontent.com/18363190/125044795-9be61800-e09c-11eb-9e1d-fd198266a111.png)

Does is save the session only when exiting the app manually? Is there a way to prevent it in the future?

**Comment by mortuusars** [comment]
> Does is save the session only when exiting the app manually?

No, it saves every 3 seconds.

I believe that this is quite a rare thing. The only way I see it happening is system shutdown at a very moment that it is saving the records file. Theoretically it can happen again, but the window is very small, a couple of milliseconds, when the file is being written to.

I can prevent it by keeping a number of versions of a session file, and loading older version if it fails to load the most recent. But it would require a rewrite of how records are saved and loaded.

If it's not that critical I'd rather not fix it now. If it happens again, let me know. Maybe I'm wrong in how often it can happen.
