### ISSUE TITLE
Resizable window

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PhotoshopTimeTracker#5]
Hi! First of all, thanks for creating this app! I was looking for something like this for a long time but only your program met my requirements :D 
I work with documents which names consist of a catalog number, name, size and some other things. Because of how long those names are I can't see the whole text. Can you please add an option to resize the window horizontally?
Thanks!

**Comment by mortuusars** [comment]
Hi! Thanks for using it :) I've actually added ability to resize the window a while ago, but stopped working on the app and didn't released it. 
I've published a new release, it works a little bit differently in how it tracks PS documents. I've tested it in PS CC2019 and it may not work in other versions. 
Try it and let me know if it is working and if you find any issues.
