### ISSUE TITLE
Crash with PS 22.4.2

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PhotoshopTimeTracker#6]
Hi, thanks for releasing the update! Resizing works flawlessly but when I focus PS the Time Tracker crashes. I'm using the latest PS CC release (22.4.2). Here is the error message. Before running the app I have installed the latest .NET desktop runtime (5.0.7).
![image](https://user-images.githubusercontent.com/18363190/123912650-99d5d800-d97d-11eb-8feb-e36ab87a1fea.png)
Also, 'About' doesn't seem to work.
Thanks!

**Comment by mortuusars** [comment]
I'll try to fix this, thanks for the report.

**Comment by mortuusars** [comment]
I've published a new release, hope this issue is fixed now. If not - in settings you can enable "Legacy tracking". It works like an old version.
