### ISSUE TITLE
Removing entries

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PhotoshopTimeTracker#8]
Thank you for making it work on the latest version, it's perfect now!
Did you also change the way to remove recorded entries? Double clicking doesn't seem to work now.
Also, could you add a function to re-enable auto height snapping? If you change the window height manually the only way to do it is by restarting the app. Thank you!

**Comment by mortuusars** [comment]
Press "Delete" key to remove selected items. You can select multiple with Ctrl and Shift.
Right click on the bottom resize border will reset height and re-enable snapping to items. Sometimes you need to click twice for auto height to work. This should be fixed in next release.

**Comment by wertos97** [comment]
I see now, thank you!
