### ISSUE TITLE
Space between name and time

### ISSUE THREAD

**Issue by wertos97** [mortuusars/PhotoshopTimeTracker#9]
It looks like the space between file name and time spent scales along with window width.

![image](https://user-images.githubusercontent.com/18363190/124250037-c1b37000-db24-11eb-98af-22d0068886c6.png)
Here you can see the space's width is similar to the height of the text box.

![image](https://user-images.githubusercontent.com/18363190/124250350-19ea7200-db25-11eb-9ca1-307c220d8f44.png)
However, when the window is wider the space also becomes bigger.

Could you also make it end with a fade instead of a sharp edge?

P.S. 
Please add a PayPal link to your bio!

**Comment by mortuusars** [comment]
I'll try to fix it.

PayPal does not work in my country, I only have Payoneer, and if I understand it right, you can't just link it anywhere, it's harder with them.

**Comment by wertos97** [comment]
Oh... Is there any other way I can repay you for your amazing work?

**Comment by mortuusars** [comment]
It's not necessary. It is enough for me that you found my app useful :). Thanks.
